[tool.black]
line-length = 80
target-version = ['py39']
exclude = '/.*(__pycache__).*/'

[tool.setuptools]
packages = ["spych"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "spych"
version = "4.3.0"
description = "Communicate with your favorite AI model by talking to it."
authors = [
    {name="Connor Makowski", email="conmak@mit.edu"}
]
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    'License :: OSI Approved :: MIT License',
    "Operating System :: OS Independent",
]
dependencies = [
    "claude_agent_sdk>=0.1.45,<1.0.0",
    "kokoro>=0.9.4,<1.0.0; python_version < '3.13'",
    "chatterbox-tts>=0.1.7,<1.0.0; python_version >= '3.13'",
    # Numba is necessary to build chatterbox
    "numba>=0.61; python_version >= '3.13'",
    "faster-whisper>=1.2.1,<2.0.0",
    "pvrecorder>=1.2.7,<2.0.0",
    "requests>=2.32.5,<3.0.0",
    "silero_vad>=6.2.1,<7.0.0",
    "pygame-ce>=2.5.7,<3.0.0"
]

[project.optional-dependencies]
dev = [
    "autoflake>=2.3.1",
    "black>=25.1.0",
    "build>=1.4.0",
    "twine>=6.2.0",
    "pdoc>=16.0.0",
    "pytest>=8.0.0",
    "pytest-timeout>=2.3.1",
    "nox>=2024.3.2",
]

[tool.pytest.ini_options]
testpaths = ["test"]
python_files = ["*.py"]
timeout = 30
markers = [
    "kokoro: tests for kokoro TTS backend",
    "chatterbox: tests for chatterbox TTS backend",
]

[project.scripts]
spych = "spych.cli:main"

[project.urls]
"Homepage" = "https://github.com/connor-makowski/spych"
"Bug Tracker" = "https://github.com/connor-makowski/spych/issues"
"Documentation" = "https://connor-makowski.github.io/spych/spych/index.html"
